# Generated by Django 3.2 on 2021-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('customer', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('purchases', models.JSONField()),
            ],
        ),
    ]
